version: '4'

services:
  api_fast:
    build:
      context: ./api_fast
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=sqlite:///data/api_fast_db.sqlite
    volumes:
      - db_data:/data

  api_auth:
    build:
      context: ./api_auth
    ports:
      - "5002:5002"
    depends_on:
      - db
    environment:
      - DATABASE_URL=sqlite:///data/api_auth_db.sqlite
    volumes:
      - db_data:/data

  api_front:
    build:
      context: ./api_front
    ports:
      - "5001:5001"
    depends_on:
      - api_fast
      - api_auth
    environment:
      - API_FAST_URL=http://api_fast:5000
      - API_AUTH_URL=http://api_auth:5002
    volumes:
      - db_data:/data

  db:
    image: nouchka/sqlite3:latest
    volumes:
      - db_data:/data
      - ./init_db.sh:/docker-entrypoint-initdb.d/init_db.sh
      - ./database.db:/data/database.db
      - ./users.db:/data/users.db
    entrypoint: /docker-entrypoint-initdb.d/init_db.sh

volumes:
  db_data: